# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bee4373719235a14afde82631a8246279c20f04dccb2ed4ee170bef714737a1fa0cbeafbe018342d29340b54e0a808b00c49a48d05bbbdde2f18d791b9ad4dac

test:
  secret_key_base: 1efbe0f0569be53091ae3353f0ebc02a43f0d098083496e9af286d0a3e7e74e9fadb4c5330da42212a9b7d0dd9e55172253f271107a115133992431d5d8bff05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
